### ISSUE TITLE
Logo design

### ISSUE THREAD

**Issue by Batarian711** [dreamingechoes/awesome-mental-health#1]
Hi. I am a graphic designer. I like helping open-source projects. I want to give you a logo to use in the readme file. Do you have an idea? What do you say?

**Comment by dreamingechoes** [comment]
Hi @Batarian711!

Omg, that would be such an awesome contribution to the project! I love the idea 😄 

I have to be honest with you, graphic design is not my strength so I don't have any clear idea for a logo design 😅 Maybe something simple and clean which reflects the ideas of mental awareness and self-care, what do you think?

Thank you very much for this proposition! 🤗

**Comment by Batarian711** [comment]
I want to give you my idea. Hold on.

**Comment by Batarian711** [comment]
I have designed a logo to represent your project and the apartments represent money. The green sign represents the gain. Which one do you prefer? Anything you'd like to add?
![awesome](https://user-images.githubusercontent.com/41051393/47118240-60151f80-d26f-11e8-97a5-46201855fd9f.jpg)

**Comment by dreamingechoes** [comment]
Hi @Batarian711!

Sorry for the late response, I was too busy the last week at work and I couldn't take care of the issue properly. 

Looks nice! but finally a friend of mine sent me another logo and I already told him I was going to use his logo, sorry for the inconvenience.

Anyways, thank you very much for the issue and the contribution, I really appreciate it a lot! 😊💖

Greetings!
