### ISSUE TITLE
Link to canonical version of my articles

### ISSUE THREAD

**Issue by daragh99** [dreamingechoes/awesome-mental-health#11]
Hey! I love that two of my articles are on this list. It would be even more amazing if they could link to the canonical articles on my own site (codingmindfully.com)

www.codingmindfully.com/stress 
www.codingmindfully.com/impostor

I can do a PR.

**Comment by dreamingechoes** [comment]
Hi @daragh99!

It would be awesome if you can create a PR to change the links of your articles! Or if you prefer, I can make the changes myself, just tell me and I'll do it.

Btw, sorry for adding your articles from other sites, it was where I read them 🙇 🙏 😅 

Greetings! 😊

**Comment by daragh99** [comment]
Great. Do you need to add me to the repo? I tried pushing a PR yesterday
but no joy!

**Comment by dreamingechoes** [comment]
Uhm, it's weird, the PRs are open for everyone, with no need to add the user to the repo 🤔 Don't worry, I'll add the changes myself and I'll close the issue once the changes are merged into master branch! 😊

**Comment by dreamingechoes** [comment]
I've just merged pull request #12, which change the links for your resources, so I close this issue!

Thank you for your awesome articles! 🤗

**Comment by daragh99** [comment]
Really amazing! Thanks for that. Really great list.

**Comment by daragh99** [comment]
I see you are on dev.to - my instinct is to create a post linking to your
repo, would you be OK with that? I have 3.5k followers on there. I'd also
be interested in sharing it with my mailing list.

I'm about to launch a course for developers, it's called The Mindful
Developer, check out the signup page here:

http://codingmindfully.com/the-mindful-developer-course-signup/

Daragh

**Comment by dreamingechoes** [comment]
Hi @daragh99!

Of course, you can share the link to the repo wherever you want, you are part of it! :smile: Feel free to post it elsewhere. I'll be looking forward to that post and your new course!

Thank you! :hugs:
