### ISSUE TITLE
Generalize and add disclaimers.

### ISSUE THREAD

**Issue by agucova** [dreamingechoes/awesome-mental-health#17]
I think this list could seriously benefit from broadening its scope to Mental Health in general and not just the software industry. For this purpose, I propose that industry-specific resources be moved to their own heading.

On the other hand, I think we could add a small disclaimer regarding evidence-based resources on CONTRIBUTING.md, I think it's important to make clear that resources should have a background in evidence-based psychotherapy (and not just pop psychology).

Finally, the list could take a broader scope in self-help tools. I'm not sure if the awesome manifesto puts any restriction on introductions, but the list could include a short disclaimer on how (and how not) to use the resources, and getting  professional help if necessary.

**Comment by agucova** [comment]
I'm thinking of something in the lines of:

> This list compiles several self-help resources we've personally found useful for a range of mental health problems, but in no way are they a replacement of professional help, psychotherapy or pharmacotherapy. **We're not experts** and even if we were, most of these tools are meant as an aid to therapy. 
>
>**If you're in a crisis, please see [here](https://twloha.com/find-help/international-resources/) for resources in your country.**

**Comment by agucova** [comment]
As for CONTRIBUTING.md:
> When adding a resource, please keep in mind the evidence backing up its use. Especially when talking about therapy, it's important that there is **high-quality clinical evidence** for it. Small tools or apps, and articles of personal experience are exempt from this.

**Comment by dreamingechoes** [comment]
Hi @agucova!

This looks like an awesome idea to add to the project! Do you want to create a PR to add the information? If not, I can work on it :smile: 

Thank you very much! :hugs:

**Comment by agucova** [comment]
Sorry for the late reply, I'll be making a pull request soon with a first pass on the updates.

**Comment by agucova** [comment]
That's the first step, I added the disclaimers and made several small changes to the README and CONTRIBUTING.

What's more involved is organizing the resources themselves, I'll be working on that on another pull request.

**Comment by Alkalit** [comment]
I'm disagreed with the OP. My considirations:

- First of all, the `awesome <name>` initiative came from IT-society where is its goal to gather and group useful sources in specific themes. Like `awesome python`, `awesome javascript` and so on.

- Broadering the theme of this repo to "Mental Health in general" will eventually turn it into a list of study literature of a psychologist/psychiatrist. The narrow of the topic allows to keep it relativly small. Or at least not to grow exponentially.

- IT-professionals have their specific problems and nuances. For me as for a programmer it is for example "burningout"-s which I faced my self. Or for example remote work which also can give you more stress than fun if you can't adapt to it. And solutions for this problems for me as for an IT-specialist could be different that for other people.

**Comment by Alkalit** [comment]
I think the better way, which would be more in awesome project spirit, is to make vice versa - add a small "general mental health" section. By analogy with other `awesome` projects - you have python awesome list wich has a few django links, but if you need more django stuff you go in a dedicated `awesome django`.

**Comment by agucova** [comment]
@Alkalit As for your first consideration, the awesome project has emphatically tried to promote non-tech lists for a long time now (see [this](https://github.com/sindresorhus/awesome/issues/732) issue), with lists such as [Awesome Economics](https://github.com/antontarasenko/awesome-economics), [Awesome Music](https://github.com/ciconia/awesome-music#readme),[ Awesome Agriculture](https://github.com/beaorn/awesome-agriculture#readme) and so on. Although the project did start as IT-specific, it has gone a lot further since then.

As for the second consideration, there are countless lists with very broad topics, what's important is to clarify its scope and only add "awesome" stuff, not just a compilation of every resource in the field. If we keep it narrowed to self help (for which awesome content is really not that abundant), there is no reason as to why it should grow exponentially. The scope could also be narrowed even further to just digital tools for self-help, I'm thinking of CBT chatbots, open source apps, open books, and things like that.

Finally, I completely agree that there are a lot of nuances that are industry-specific to IT and programmers, but as I suggested initially, we could simply move it to its own category (with the caveat being that it'll require a big overhaul of the list).

**Comment by dreamingechoes** [comment]
I'm going to close this issue because it has been tackled on https://github.com/dreamingechoes/awesome-mental-health/pull/18 PR already. Thank you @agucova and @Alkalit! 😄
