### ISSUE TITLE
Add "if me"

### ISSUE THREAD

**Issue by jaredreich** [dreamingechoes/awesome-mental-health#7]
https://github.com/ifmeorg/ifme
@julianguyen

**Comment by julianguyen** [comment]
Thanks, that would be great! Feel free to put us under organizations! :D

> if-me.org is an open source mental health communication app that allows people to share their mental health experiences with loved ones.

**Comment by dreamingechoes** [comment]
Hi @jaredreich and @julianguyen!

Thank you for this contribution! :blush: :sparkling_heart:  I just added [if-me](https://if-me.org) to the list, so I close the issue!

Greetings!
